### ISSUE TITLE
Emerald block not emitting light

### ISSUE THREAD

**Issue by LukasMFR** [MazeWave/Vanilla-Raytraced#1]
Hi,
First let me tell you that this pack looks very nice with Minecraft RTX as it does not change the default texture (compared to other packs) but you said you took textures from VNR for 1.12, you should use the new ones from the new VNR.

And as you can see in that image the emerald block is not emitting light.

![image](https://user-images.githubusercontent.com/41242166/99152756-08428000-26a4-11eb-8eb0-13589b1ff638.png)

**Comment by MazeWave** [comment]
Hi @LukasAppleFan,
For the emerald, it will be **added** in the next update and you will be credited in the changelog. 🚀 
About using poudingue normals map from Vanilla Renewed 1.14, I'm not going to use these maps because I'm creating my own.

I give you this while waiting for the next update : http://www.mediafire.com/file/jyjbow6a9z3nn6m/Vanilla_Raytraced_Gift_Addon.mcpack/file

Thank you for opening this issue. Have a good day.

**Comment by LukasMFR** [comment]
RGB goodness thanks !

![image](https://user-images.githubusercontent.com/41242166/99180013-e63c1280-2722-11eb-8a91-a96b0f170a54.png)
